name: APE DEV - Build and deploy ASP.Net Core app to Azure Web App

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore NuGet packages
        run: dotnet restore Ape/Ape.csproj

      - name: Build com dotnet
        run: dotnet build Ape/Ape.csproj --configuration Release

      - name: Publicar app
        run: dotnet publish Ape/Ape.csproj -c Release -o ape-dev

      - name: Upload dos artefatos
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ape-dev

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Baixar artefato do job de build
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login no Azure com OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2B3558BE022246288EC535A3FE6CB6E7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B440CBE08A9441B68FA3B56E3875DC90 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BEBAB417AC004C33ADCFEC068F0272ED }}

      - name: Deploy para Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ape-dev'
          package: .