name: APE DEV - Build and deploy ASP.Net Core app to Azure Web App

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore NuGet packages
        run: dotnet restore Ape/Ape.csproj

      - name: Build com dotnet
        run: dotnet build Ape/Ape.csproj --configuration Release

      - name: Publicar app
        run: dotnet publish Ape/Ape.csproj -c Release -o ape-dev

      - name: Upload dos artefatos
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ape-dev

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Baixar artefatos do build
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy no Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ape-dev'
          package: .
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_APE_DEV }}