name: APE PRD - Build and deploy ASP.Net Core app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar .NET 6
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Build do projeto
        run: dotnet build Ape/Ape.csproj --configuration Release

      - name: Publicar artefatos
        run: dotnet publish Ape/Ape.csproj -c Release -o ape

      - name: Upload dos artefatos para job de deploy
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ape

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Baixar artefatos do build
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login no Azure com OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6D5627D5066040F7AFB2F4DD2DEBEEBD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CACA0AAC479F466BA77E8FFFE2D326F2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6189CFB15F414C01B249D44427952D92 }}

      - name: Deploy no Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ape'
          package: .